import { Loader2, Sparkles } from 'lucide-react'
import { useTheme } from '../../context/ThemeContext'
import type { ReportEntry } from '../../types'

export interface ReportsViewProps {
  formName: string
  reports: ReportEntry[]
  loading: boolean
  error: string | null
  onGenerate: () => void
}

function formatTimestamp(iso: string): string {
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return iso
  return date.toLocaleString(undefined, {
    month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit',
  })
}

export function ReportsView({ formName, reports, loading, error, onGenerate }: ReportsViewProps) {
  const C = useTheme()
  const latest = reports[0]

  return (
    <div style={{ padding: '20px 28px 32px', display: 'flex', gap: 20, alignItems: 'flex-start' }}>
      <div style={{
        flex: 1.4,
        minWidth: 0,
        borderRadius: 12,
        border: `1px solid ${C.border}`,
        background: C.panel,
        padding: '20px 22px',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
          <div>
            <div style={{ fontSize: 15, fontWeight: 700, color: C.text }}>AI Safety Performance Summary</div>
            <div style={{ fontSize: 12.5, color: C.textFaint, marginTop: 2 }}>{formName} — generated by GPT-4.1</div>
          </div>
          <button
            type="button"
            onClick={onGenerate}
            disabled={loading}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              padding: '9px 16px',
              borderRadius: 8,
              border: 'none',
              background: C.accent,
              color: '#1a0f04',
              fontSize: 13,
              fontWeight: 700,
              cursor: loading ? 'default' : 'pointer',
              opacity: loading ? 0.7 : 1,
            }}
          >
            {loading ? <Loader2 size={15} /> : <Sparkles size={15} />}
            {loading ? 'Generating…' : 'Generate Report'}
          </button>
        </div>

        {error && (
          <div style={{
            padding: '12px 14px',
            borderRadius: 8,
            border: `1px solid ${C.danger}`,
            background: C.dangerBg,
            color: C.danger,
            fontSize: 13,
            marginBottom: 14,
          }}>
            {error}
          </div>
        )}

        {latest ? (
          <div>
            <div style={{ fontSize: 12, color: C.textFaint, marginBottom: 10 }}>
              Generated {formatTimestamp(latest.timestamp)}
            </div>
            <div style={{ fontSize: 14, lineHeight: 1.7, color: C.text, whiteSpace: 'pre-wrap' }}>
              {latest.text}
            </div>
          </div>
        ) : (
          <div style={{
            padding: '32px 16px',
            textAlign: 'center',
            color: C.textFaint,
            fontSize: 13.5,
          }}>
            No report generated yet. Click <strong style={{ color: C.text }}>Generate Report</strong> to create an
            AI-written Safety Performance Summary for {formName}.
          </div>
        )}
      </div>

      <div style={{
        flex: 1,
        minWidth: 0,
        borderRadius: 12,
        border: `1px solid ${C.border}`,
        background: C.panel,
        padding: '20px 22px',
      }}>
        <div style={{ fontSize: 15, fontWeight: 700, color: C.text, marginBottom: 14 }}>Report History</div>
        {reports.length === 0 ? (
          <div style={{ fontSize: 13, color: C.textFaint }}>Generated reports will be saved here for future reference.</div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {reports.map((report, idx) => (
              <div
                key={`${report.timestamp}-${idx}`}
                style={{
                  padding: '12px 14px',
                  borderRadius: 8,
                  border: `1px solid ${C.border}`,
                  background: C.panelAlt,
                }}
              >
                <div style={{ fontSize: 12, color: C.textFaint }}>{formatTimestamp(report.timestamp)}</div>
                <div style={{
                  fontSize: 13,
                  color: C.textDim,
                  marginTop: 6,
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  display: '-webkit-box',
                  WebkitLineClamp: 3,
                  WebkitBoxOrient: 'vertical',
                }}>
                  {report.text}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
